name = "joom-template"
description = "Шаблон презентаций для Joom"
tags = []
features = ["shower", "highlight.js", "mathjax"]
min_version = 0.17

[author]
  name = "Artem V. Navrotskiy"
  homepage = "https://bozaro.ru/"
